# 頭像
avatar:
  url: images/avatar.jpg # 你的头像图片地址
  rounded: true
  opacity: 1
# 字數統計
wordcount:
  enable: true
  count: true
  time: true
# UI
banner:
  enable: true
  title: 原的小站
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
