name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - hexo  # 觸發分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4   # 升級至 v4

      - name: Setup Node.js
        uses: actions/setup-node@v4   # 升級至 v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Build Hexo
        run: |
          npx hexo clean
          npx hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master   # 輸出的目標靜態檔分支